#!/bin/bash

cd ordermark-dashboard-service

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"email":"user@admin.com", "company_name":"Ordermark", "first_name":"Captain", "last_name":"America", "cellphone":"404-579-5555", "password":"password", "master_key":"26daysin", "super_admin" : true }' http://localhost:8080/api/captain/user

curl -X POST -H 'authorization: Basic b3JkZXJtYXJrOnByaW50aW5nbW9uZXk=' -H 'cache-control: no-cache' -H 'Content-Type: application/json' -H 'postman-token: f8f24c6f-ea98-aa98-f8be-98d22fdbcd89' -d '{"restaurant_name":"1 Restaurant", "restaurant_id":"abcd^1234", "restaurant_location": "Main street", "contact_name": "Billy Bob", "contact_email": "billybob@1restaurant.com", "app_id":"ordermark-app" }' http://localhost:8080/api/dashboard/restaurant/new

curl -X POST -H 'authorization: Basic b3JkZXJtYXJrOnByaW50aW5nbW9uZXk=' -H 'cache-control: no-cache' -H 'Content-Type: application/json' -H 'postman-token: f8f24c6f-ea98-aa98-f8be-98d22fdbcd89' -d '{"restaurant_name":"1 Restaurant", "restaurant_id":"abcd^1234", "restaurant_location": "Main street", "contact_name": "Billy Bob", "contact_email": "billybob@1restaurant.com", "app_id":"ordermark-app2" }' http://localhost:8080/api/dashboard/restaurant/new

curl -X POST -H 'authorization: Basic b3JkZXJtYXJrOnByaW50aW5nbW9uZXk=' -H 'cache-control: no-cache' -H 'Content-Type: application/json' -H 'postman-token: f8f24c6f-ea98-aa98-f8be-98d22fdbcd89' -d '{"restaurant_name":"1 Restaurant", "restaurant_id":"abcd^1234", "restaurant_location": "Main street", "contact_name": "Billy Bob", "contact_email": "billybob@1restaurant.com", "app_id":"ordermark-app3" }' http://localhost:8080/api/dashboard/restaurant/new

curl -X POST -H 'authorization: Basic b3JkZXJtYXJrOnByaW50aW5nbW9uZXk=' -H 'cache-control: no-cache' -H 'Content-Type: application/json' -H 'postman-token: f8f24c6f-ea98-aa98-f8be-98d22fdbcd89' -d '{"email":"user@admin.com", "app_id":"ordermark-app", "master_key":"26daysin" }' http://localhost:8080/api/captain/user/restaurants

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"customer_name":"Diana Carter", "order_details":"1\n The Spicy\nInstructions: Ranch on the side please!\n\n$11.50\n\n1\n Thick-Cut Steak Fries\n- Half Sized\n\nInstructions: Extra ranch please!\n\n$3.50\n\n1\n Chicken Tenders\n- Ranch\n\nInstructions: Extra ranch please!\n\n$6.75","provider_name":"Postmates","provider_order_id":"dd124","customer_phone":"310-555-1212","sub_total":"$10.00","delivery_fee":"$3.00","tip":"$4.00","tax":"$0.90","total":"$17.90","paid":"$17.90", "master_key":"0rdersGoHere", "date_placed":"2:55 PM", "requested_pickup_date":"ASAP Delivery", "completed": true, "cancelled": false, "app_id":"ordermark-app", "active_datetime": "2017-08-08T02:36:41.613520", "confirmed": false, "print_message": { "message": "Printed", "cause": "Was printed successfuly" } }' http://localhost:8080/api/order/order

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"customer_name":"Clark Kent", "order_details":"1\n The Spicy\nInstructions: Ranch on the side please!\n\n$11.50\n\n1\n Thick-Cut Steak Fries\n- Half Sized\n\nInstructions: Extra ranch please!\n\n$3.50\n\n1\n Chicken Tenders\n- Ranch\n\nInstructions: Extra ranch please!\n\n$6.75","provider_name":"DoorDash","provider_order_id":"dd123","customer_phone":"310-555-1212","sub_total":"$10.00","delivery_fee":"$3.00","tip":"$4.00","tax":"$0.90","total":"$17.90","paid":"$17.90", "master_key":"0rdersGoHere", "requested_pickup_date":"ASAP Delivery", "completed": false, "cancelled": false, "confirmed": true, "app_id":"ordermark-app", "refunded_datetime":"2017-08-08T02:36:41.613520", "date_placed":"3:21 PM", "printjobid": "1234567890" }' http://localhost:8080/api/order/order

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"customer_name":"Peter Parker", "order_details":"1\n Cobb Salad\nInstructions: Ranch on the side please!\n\n$11.50\n\n1\n Thick-Cut Steak Fries\n- Half Sized\n\nInstructions: Extra ranch please!\n\n$3.50\n\n1\n Chicken Tenders\n- Ranch\n\nInstructions: Extra ranch please!\n\n$6.75","provider_name":"Eat24","provider_order_id":"dd125","customer_phone":"310-555-1212","sub_total":"$10.00","delivery_fee":"$3.00","tip":"$4.00","tax":"$0.90","total":"$17.90","paid":"$17.90", "master_key":"0rdersGoHere", "requested_pickup_date":"ASAP Delivery", "completed": false, "cancelled": false, "confirmed": true, "app_id":"ordermark-app", "refunded_datetime":"2017-08-08T02:36:41.613520", "date_placed":"3:21 PM", "printjobid": "1234567890" }' http://localhost:8080/api/order/order

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"customer": {"city": "Los Angeles", "name": "Craig Kimble", "zip": "90024", "address1": "10960 Wilshire Blvd", "state": "CA", "special_instructions": "We will be on the 9th floor. Please call 206-240-7315 when you are here!"}, "meta_info": {"email_label": "Orders/Emporium Thai", "order_type": "O", "email_message_id": "160583f23f9c7aa8", "email_from": "EatStreet Orders <orders@eatstreet.com>", "email_to": "orders+emporiumthai@getordermark.com, emporiumthai@gmail.com", "email_subject": "EatStreet Order 10108621", "provider_name": "Eatstreet", "email": "orders@getordermark.com"}, "restaurant": {"restaurant_name": "Emporium Thai Cuisine"}, "confirmation_link": "https://eatstreet.com/confirm_order?order_request_id\u201835339&confirmation;_key=M9paMnYnBoChmsyL+Ko36A=", "miscellaneous": {"brand": "Eatstreet", "customer_service_number": "(866) 654-8777"}, "customer_order_id": "10108621", "order": {"total": 94.14, "confirmation_number": "0962#", "donations_detail": [], "delivery_charge": 5.0, "service_type_code": "D", "order_id": "10108621", "payment_method_description": "DO NOT CHARGE", "confirmation_telephone_number": "(866) 688-3211", "discounts_detail": [], "payment_method_code": "P", "is_revision": false, "placed_date": "06:03 PM 12/14/2017", "adjustments_detail": [], "sales_tax": 6.01, "cancelled": false, "tip": 14.43, "service_type_description": "DELIVERY", "subtotal": 68.7}, "menu_items": [{"item_name": "20. Chefs Special Pad Thai", "price": 12.95, "modifiers": [{"item_name": "Chicken", "item_number": 0}]}, {"item_name": "13. Panang Curry and Jasmine Rice", "price": 12.95, "modifiers": [{"item_name": "Chicken", "item_number": 0}, {"item_name": "White Rice", "item_number": 1}, {"item_name": "2. Mildly Spicy", "item_number": 2}]}, {"item_name": "10. Tom Yum Gai (Chicken) - Small", "price": 7.95, "modifiers": [{"item_name": "7. Spicy with Heat+", "item_number": 0}]}, {"item_name": "18. Thai Fried Rice", "price": 13.95, "modifiers": [{"item_name": "Chicken", "item_number": 0}, {"item_name": "Side of Peanut Sauce", "item_number": 1, "price": 1.0}]}, {"item_name": "15. Green Curry and Jasmine Rice", "price": 12.95, "modifiers": [{"item_name": "Chicken", "item_number": 0}, {"item_name": "Jasmine Rice", "item_number": 1}, {"item_name": "2. Mildly Spicy", "item_number": 2}]}]}' http://localhost:8080/_ah/push-handlers/order/new

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -d '{"customer": {"phone": "(415) 205-5548", "name": "Ahmed"}, "meta_info": {"email_label": "Orders/Halal Guys - San Francisco", "order_type": "O", "email_message_id": "1605c2132119e3ad", "email_from": "Caviar <sfordernotifications@trycaviar.com>", "email_to": "louise@fomothg.com, 203@fomothg.com, halalsf@getordermark.com", "email_subject": "San Francisco [ASAP] Caviar Delivery Order 3816", "provider_name": "Caviar", "email": "orders3@getordermark.com"}, "restaurant": {}, "confirmation_link": null, "miscellaneous": {"brand": "Caviar"}, "customer_order_id": "3816", "order": {"total": 21.12, "donations_detail": [], "delivery_by": "2:01PM", "order_id": "3816", "payment_method_description": "Prepaid", "estimated_date": "2:01PM", "discounts_detail": [], "service_type_code": "P", "payment_method_code": "P", "is_revision": false, "placed_date": "Friday, 12/15/2017 at 01:41PM PST", "adjustments_detail": [], "sales_tax": 1.65, "cancelled": false, "service_type_description": "Courier Pickup at 2:01PM", "subtotal": 19.47}, "menu_items": [{"item_name": "Gyro Platter", "item_number": 0, "price": 16.48, "modifiers": [{"item_name": "- Add Extra Meat", "item_number": 0}], "quantity": 1}, {"item_name": "Baklava", "item_number": 1, "price": 2.99, "quantity": 1}]}' http://localhost:8080/_ah/push-handlers/order/new

curl -X POST -H 'Content-Type: application/json' -H 'Postman-Token: 58d62c69-662e-8235-3c19-7593422a5d2a' -H 'authorization: Basic b3JkZXJtYXJrOm1vbmV5cHJpbnRpbmdtYWNoaW5l' -H 'X-Appengine-Inbound-Appid: test_app_id' -H 'ordermark-appid: 123' -d '{"customer": {"phone": "(818) 414-8539", "name": "Zander 6"}, "meta_info": {"app_id": "ordermark-app", "order_type": "O", "email_subject": "Delivery for Allyson from Veggie Grill (Encino)", "email_to": "veggiegrillencino@getordermark.com", "provider_name": "Doordash", "email_message_id": "1614ea459516372b", "email_from": "\"DoorDash\" <orders@doordash.com>", "email": "orders4@getordermark.com"}, "menu_items": [{"item_number": 0, "item_name": "Buffalo Wings", "price": 7.5, "item_type": "Shares", "quantity": 1}, {"item_number": 1, "item_name": "Tempura Green Bean Stack", "price": 7.5, "item_type": "Shares", "quantity": 1}, {"item_number": 2, "item_name": "Mac-N-Cheese", "price": 4.95, "item_type": "Comfort Favorites", "quantity": 1}, {"item_number": 3, "item_name": "Mint Lemonade Strawberry Lemonade", "price": 2.5, "item_type": "Beverages", "special_instructions": "strawberry", "quantity": 1}], "customer_order_id": "44947107", "restaurant": {"restaurant_name": "Veggie Grill (Encino)"}, "confirmation_link": "https://doordash.com/api/stores/5673/deliveries/kris7uk7/confirm/", "miscellaneous": {"brand": "Doordash"}, "issues": [], "order": {"is_revision": false, "payment_method_code": "P", "delivery_by": "4:14 PM Today (Wed Jan 31)", "order_id": "44947107", "requested_date_label": "Pickup Time", "sales_tax": 2.13, "discounts_detail": [], "service_type_code": "D", "payment_method_description": "Prepaid", "placed_date": "Wed, Jan 31 at 3:54 PM", "adjustments_detail": [], "service_type_description": "Delivery", "cancelled": false, "total": 24.58, "subtotal": 22.45, "donations_detail": []}}' localhost:8080/_ah/push-handlers/order/new
